// DrugOS Screen Registry - Maps all 232 screen IDs to metadata

export interface ScreenMeta {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  description: string;
  icon: string;
}

export const screenCategories = [
  { id: 'PUB', label: 'Public', icon: 'Globe' },
  { id: 'AUTH', label: 'Authentication', icon: 'Lock' },
  { id: 'DASH', label: 'Dashboards', icon: 'LayoutDashboard' },
  { id: 'CORE', label: 'Drug Repurposing', icon: 'Search' },
  { id: 'DATA', label: 'Data Sources', icon: 'Database' },
  { id: 'COLLAB', label: 'Collaboration', icon: 'Users' },
  { id: 'BILL', label: 'Billing', icon: 'CreditCard' },
  { id: 'INV', label: 'Investor', icon: 'TrendingUp' },
  { id: 'ADMIN', label: 'Admin', icon: 'Shield' },
  { id: 'LEGAL', label: 'Legal & Compliance', icon: 'Scale' },
  { id: 'DEV', label: 'Developer', icon: 'Code' },
  { id: 'SET', label: 'Settings', icon: 'Settings' },
  { id: 'SUPP', label: 'Support', icon: 'HelpCircle' },
  { id: 'MISC', label: 'Miscellaneous', icon: 'FileQuestion' },
] as const;

export const screens: ScreenMeta[] = [
  // PUBLIC
  { id: 'PUB-01', name: 'Homepage', category: 'PUB', categoryLabel: 'Public', description: 'Landing page with search, stats, how it works', icon: 'Globe' },
  { id: 'PUB-02', name: 'Pricing', category: 'PUB', categoryLabel: 'Public', description: 'Subscription tiers and cost calculator', icon: 'Globe' },
  { id: 'PUB-03', name: 'Disease Search Feature', category: 'PUB', categoryLabel: 'Public', description: 'Feature page for disease search & candidate ranking', icon: 'Globe' },
  { id: 'PUB-04', name: 'Knowledge Graph Feature', category: 'PUB', categoryLabel: 'Public', description: 'Feature page for knowledge graph explorer', icon: 'Globe' },
  { id: 'PUB-05', name: 'Safety Profiling Feature', category: 'PUB', categoryLabel: 'Public', description: 'Feature page for safety and off-target profiling', icon: 'Globe' },
  { id: 'PUB-06', name: 'Evidence Reports Feature', category: 'PUB', categoryLabel: 'Public', description: 'Feature page for evidence packages', icon: 'Globe' },
  { id: 'PUB-07', name: 'API Dev Tools Feature', category: 'PUB', categoryLabel: 'Public', description: 'Feature page for API and developer tools', icon: 'Globe' },
  { id: 'PUB-08', name: 'About', category: 'PUB', categoryLabel: 'Public', description: 'Team, mission, timeline', icon: 'Globe' },
  { id: 'PUB-09', name: 'Security & Trust', category: 'PUB', categoryLabel: 'Public', description: 'Security practices, compliance, certifications', icon: 'Globe' },
  { id: 'PUB-10', name: 'Status Page', category: 'PUB', categoryLabel: 'Public', description: 'Real-time system status', icon: 'Globe' },
  { id: 'PUB-11', name: 'Blog & News', category: 'PUB', categoryLabel: 'Public', description: 'Publications, updates, announcements', icon: 'Globe' },
  { id: 'PUB-12', name: 'Contact', category: 'PUB', categoryLabel: 'Public', description: 'Sales inquiry, support, partner forms', icon: 'Globe' },
  { id: 'PUB-13', name: 'Careers', category: 'PUB', categoryLabel: 'Public', description: 'Job listings and applications', icon: 'Globe' },
  { id: 'PUB-14', name: 'Case Studies', category: 'PUB', categoryLabel: 'Public', description: 'Customer success stories', icon: 'Globe' },
  { id: 'PUB-15', name: 'Documentation Portal', category: 'PUB', categoryLabel: 'Public', description: 'Public docs and getting started', icon: 'Globe' },
  { id: 'PUB-16', name: 'Changelog', category: 'PUB', categoryLabel: 'Public', description: 'Product updates and releases', icon: 'Globe' },
  { id: 'PUB-17', name: 'Community', category: 'PUB', categoryLabel: 'Public', description: 'Community forum and discussions', icon: 'Globe' },
  { id: 'PUB-18', name: 'Partners', category: 'PUB', categoryLabel: 'Public', description: 'Partner network and integrations', icon: 'Globe' },
  { id: 'PUB-19', name: 'Press Kit', category: 'PUB', categoryLabel: 'Public', description: 'Media resources and brand assets', icon: 'Globe' },
  // AUTH
  { id: 'AUTH-01', name: 'Login', category: 'AUTH', categoryLabel: 'Authentication', description: 'Email, SSO, OIDC login', icon: 'Lock' },
  { id: 'AUTH-02', name: 'Registration', category: 'AUTH', categoryLabel: 'Authentication', description: 'Signup with role selection', icon: 'Lock' },
  { id: 'AUTH-03', name: 'Forgot Password', category: 'AUTH', categoryLabel: 'Authentication', description: 'Password reset request', icon: 'Lock' },
  { id: 'AUTH-04', name: 'Reset Password', category: 'AUTH', categoryLabel: 'Authentication', description: 'Set new password', icon: 'Lock' },
  { id: 'AUTH-05', name: 'MFA Challenge', category: 'AUTH', categoryLabel: 'Authentication', description: 'Multi-factor authentication', icon: 'Lock' },
  { id: 'AUTH-06', name: 'Email Verification', category: 'AUTH', categoryLabel: 'Authentication', description: 'Verify email address', icon: 'Lock' },
  { id: 'AUTH-07', name: 'Academic Verification', category: 'AUTH', categoryLabel: 'Authentication', description: 'Verify .edu email for free tier', icon: 'Lock' },
  { id: 'AUTH-08', name: 'Organization Selection', category: 'AUTH', categoryLabel: 'Authentication', description: 'Select org after SSO login', icon: 'Lock' },
  { id: 'AUTH-09', name: 'SSO Callback', category: 'AUTH', categoryLabel: 'Authentication', description: 'SSO authentication callback', icon: 'Lock' },
  { id: 'AUTH-10', name: 'Onboarding Welcome', category: 'AUTH', categoryLabel: 'Authentication', description: 'Welcome screen for new users', icon: 'Lock' },
  { id: 'AUTH-11', name: 'Onboarding Role Selection', category: 'AUTH', categoryLabel: 'Authentication', description: 'Choose role during onboarding', icon: 'Lock' },
  { id: 'AUTH-12', name: 'Onboarding Workspace Setup', category: 'AUTH', categoryLabel: 'Authentication', description: 'Configure workspace', icon: 'Lock' },
  { id: 'AUTH-13', name: 'Onboarding Team Invite', category: 'AUTH', categoryLabel: 'Authentication', description: 'Invite team members', icon: 'Lock' },
  { id: 'AUTH-14', name: 'Admin Approval Pending', category: 'AUTH', categoryLabel: 'Authentication', description: 'Waiting for admin approval', icon: 'Lock' },
  { id: 'AUTH-15', name: 'Account Locked', category: 'AUTH', categoryLabel: 'Authentication', description: 'Account locked after failed attempts', icon: 'Lock' },
  // DASH
  { id: 'DASH-01', name: 'Personal Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'User\'s default landing page', icon: 'LayoutDashboard' },
  { id: 'DASH-02', name: 'Organization Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Org admin overview', icon: 'LayoutDashboard' },
  { id: 'DASH-03', name: 'Project Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Project-specific overview', icon: 'LayoutDashboard' },
  { id: 'DASH-04', name: 'Usage Analytics', category: 'DASH', categoryLabel: 'Dashboards', description: 'Usage metrics and trends', icon: 'LayoutDashboard' },
  { id: 'DASH-05', name: 'Research Output Tracker', category: 'DASH', categoryLabel: 'Dashboards', description: 'Track research outputs and publications', icon: 'LayoutDashboard' },
  { id: 'DASH-06', name: 'Team Activity Feed', category: 'DASH', categoryLabel: 'Dashboards', description: 'Real-time team activity', icon: 'LayoutDashboard' },
  { id: 'DASH-07', name: 'Pipeline Analytics', category: 'DASH', categoryLabel: 'Dashboards', description: 'Drug pipeline analytics', icon: 'LayoutDashboard' },
  { id: 'DASH-08', name: 'Market Opportunity', category: 'DASH', categoryLabel: 'Dashboards', description: 'Market analysis dashboard', icon: 'LayoutDashboard' },
  { id: 'DASH-09', name: 'Competitive Intelligence', category: 'DASH', categoryLabel: 'Dashboards', description: 'Competitor tracking and analysis', icon: 'LayoutDashboard' },
  { id: 'DASH-10', name: 'Alert Center', category: 'DASH', categoryLabel: 'Dashboards', description: 'Centralized alerts and notifications', icon: 'LayoutDashboard' },
  { id: 'DASH-11', name: 'Rare Disease Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Customized rare disease view', icon: 'LayoutDashboard' },
  { id: 'DASH-12', name: 'Investor Analytics', category: 'DASH', categoryLabel: 'Dashboards', description: 'Investor-focused analytics', icon: 'LayoutDashboard' },
  { id: 'DASH-13', name: 'CRO Project Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'CRO multi-sponsor view', icon: 'LayoutDashboard' },
  { id: 'DASH-14', name: 'Compliance Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Compliance status overview', icon: 'LayoutDashboard' },
  { id: 'DASH-15', name: 'Data Health Dashboard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Data quality and freshness metrics', icon: 'LayoutDashboard' },
  { id: 'DASH-16', name: 'Executive Summary', category: 'DASH', categoryLabel: 'Dashboards', description: 'High-level executive view', icon: 'LayoutDashboard' },
  { id: 'DASH-17', name: 'KPI Scorecard', category: 'DASH', categoryLabel: 'Dashboards', description: 'Key performance indicators', icon: 'LayoutDashboard' },
  // CORE
  { id: 'CORE-01', name: 'Disease Search', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Main search interface', icon: 'Search' },
  { id: 'CORE-02', name: 'Search Results', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Ranked candidate table', icon: 'Search' },
  { id: 'CORE-03', name: 'Candidate Detail', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Full candidate view with tabs', icon: 'Search' },
  { id: 'CORE-04', name: 'Mechanistic Pathway', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Interactive pathway visualization', icon: 'Search' },
  { id: 'CORE-05', name: 'Safety Profile', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Safety dashboard for a drug', icon: 'Search' },
  { id: 'CORE-06', name: 'Knowledge Graph Explorer', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Standalone graph exploration tool', icon: 'Search' },
  { id: 'CORE-07', name: 'Clinical Trial Search', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Search ClinicalTrials.gov data', icon: 'Search' },
  { id: 'CORE-08', name: 'IP & Patent Status', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Intellectual property assessment', icon: 'Search' },
  { id: 'CORE-09', name: 'Evidence Package Builder', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Assemble evidence packages', icon: 'Search' },
  { id: 'CORE-10', name: 'Report Generation', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Generate and preview reports', icon: 'Search' },
  { id: 'CORE-11', name: 'Candidate Pathway Tab', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Pathway details for a candidate', icon: 'Search' },
  { id: 'CORE-12', name: 'Candidate Safety Tab', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Safety details for a candidate', icon: 'Search' },
  { id: 'CORE-13', name: 'Candidate Clinical Tab', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Clinical trial details for a candidate', icon: 'Search' },
  { id: 'CORE-14', name: 'Candidate IP Tab', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'IP details for a candidate', icon: 'Search' },
  { id: 'CORE-15', name: 'Candidate Evidence Tab', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Evidence details for a candidate', icon: 'Search' },
  { id: 'CORE-16', name: 'Advanced Search', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Multi-filter advanced search', icon: 'Search' },
  { id: 'CORE-17', name: 'Saved Queries', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Manage saved search queries', icon: 'Search' },
  { id: 'CORE-18', name: 'Drug Comparison', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Compare multiple drug candidates', icon: 'Search' },
  { id: 'CORE-19', name: 'Drug-Drug Interaction', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Check drug-drug interactions', icon: 'Search' },
  { id: 'CORE-20', name: 'Molecular Similarity', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Molecular structure similarity search', icon: 'Search' },
  { id: 'CORE-21', name: 'Composite Score Breakdown', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Detailed score decomposition', icon: 'Search' },
  { id: 'CORE-22', name: 'Disease Detail', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Comprehensive disease overview', icon: 'Search' },
  { id: 'CORE-23', name: 'Shortlist & Collections', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Manage candidate shortlists', icon: 'Search' },
  { id: 'CORE-24', name: 'Query History', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Past search history', icon: 'Search' },
  { id: 'CORE-25', name: 'Batch Query', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Run queries for multiple diseases', icon: 'Search' },
  { id: 'CORE-26', name: 'Prediction Explorer', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Explore AI predictions in detail', icon: 'Search' },
  { id: 'CORE-27', name: 'Evidence Timeline', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Evidence timeline for a drug-disease pair', icon: 'Search' },
  { id: 'CORE-28', name: 'Mechanism of Action', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Detailed MoA view', icon: 'Search' },
  { id: 'CORE-29', name: 'Regulatory Pathway', category: 'CORE', categoryLabel: 'Drug Repurposing', description: 'Regulatory pathway assessment', icon: 'Search' },
  // DATA
  { id: 'DATA-01', name: 'Data Source Overview', category: 'DATA', categoryLabel: 'Data Sources', description: 'Overview of all data sources', icon: 'Database' },
  { id: 'DATA-02', name: 'Knowledge Graph Statistics', category: 'DATA', categoryLabel: 'Data Sources', description: 'Graph metrics and statistics', icon: 'Database' },
  { id: 'DATA-03', name: 'Entity Resolution', category: 'DATA', categoryLabel: 'Data Sources', description: 'Cross-source entity matching', icon: 'Database' },
  { id: 'DATA-04', name: 'Data Quality Monitor', category: 'DATA', categoryLabel: 'Data Sources', description: 'Data quality metrics and alerts', icon: 'Database' },
  { id: 'DATA-05', name: 'Data Ingestion Pipeline', category: 'DATA', categoryLabel: 'Data Sources', description: 'Data pipeline status and logs', icon: 'Database' },
  { id: 'DATA-06', name: 'Graph Schema Viewer', category: 'DATA', categoryLabel: 'Data Sources', description: 'View knowledge graph schema', icon: 'Database' },
  { id: 'DATA-07', name: 'Edge Evidence Browser', category: 'DATA', categoryLabel: 'Data Sources', description: 'Browse evidence for graph edges', icon: 'Database' },
  { id: 'DATA-08', name: 'Node Degree Distribution', category: 'DATA', categoryLabel: 'Data Sources', description: 'Graph node degree analysis', icon: 'Database' },
  { id: 'DATA-09', name: 'Data Freshness Report', category: 'DATA', categoryLabel: 'Data Sources', description: 'Data sync status and freshness', icon: 'Database' },
  { id: 'DATA-10', name: 'Cross-Source Reconciliation', category: 'DATA', categoryLabel: 'Data Sources', description: 'Reconcile data across sources', icon: 'Database' },
  // COLLAB
  { id: 'COLLAB-01', name: 'Team Members', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Manage team members', icon: 'Users' },
  { id: 'COLLAB-02', name: 'Project Workspace', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Project collaboration workspace', icon: 'Users' },
  { id: 'COLLAB-03', name: 'Shared Queries', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Share and discover queries', icon: 'Users' },
  { id: 'COLLAB-04', name: 'Team Annotations', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Annotate candidates as a team', icon: 'Users' },
  { id: 'COLLAB-05', name: 'Discussion Threads', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Discussion threads on candidates', icon: 'Users' },
  { id: 'COLLAB-06', name: 'File Sharing', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Share files and documents', icon: 'Users' },
  { id: 'COLLAB-07', name: 'Access Controls', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Project-level access controls', icon: 'Users' },
  { id: 'COLLAB-08', name: 'Activity Timeline', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Team activity timeline', icon: 'Users' },
  { id: 'COLLAB-09', name: 'Notification Center', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Mentions and notifications', icon: 'Users' },
  { id: 'COLLAB-10', name: 'Collaborative Evidence', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Collaborative evidence packages', icon: 'Users' },
  { id: 'COLLAB-11', name: 'Team Dashboard', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Team overview dashboard', icon: 'Users' },
  { id: 'COLLAB-12', name: 'External Sharing', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Share with external partners', icon: 'Users' },
  { id: 'COLLAB-13', name: 'Community Collaboration', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Community features for rare disease', icon: 'Users' },
  { id: 'COLLAB-14', name: 'Multi-Agency Sharing', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Secure multi-agency data sharing', icon: 'Users' },
  { id: 'COLLAB-15', name: 'CRO Sponsor Isolation', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'CRO project isolation view', icon: 'Users' },
  { id: 'COLLAB-16', name: 'Shared Templates', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Shared report and query templates', icon: 'Users' },
  { id: 'COLLAB-17', name: 'Version History', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Document version history', icon: 'Users' },
  { id: 'COLLAB-18', name: 'Review Workflow', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Peer review workflow', icon: 'Users' },
  { id: 'COLLAB-19', name: 'Research Notes', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Shared research notes', icon: 'Users' },
  { id: 'COLLAB-20', name: 'Export & Transfer', category: 'COLLAB', categoryLabel: 'Collaboration', description: 'Export and transfer data', icon: 'Users' },
  // BILL
  { id: 'BILL-01', name: 'Subscription Management', category: 'BILL', categoryLabel: 'Billing', description: 'Plan and subscription management', icon: 'CreditCard' },
  { id: 'BILL-02', name: 'Usage & Billing Dashboard', category: 'BILL', categoryLabel: 'Billing', description: 'Usage metrics and billing', icon: 'CreditCard' },
  { id: 'BILL-03', name: 'Licensing Deal Workflow', category: 'BILL', categoryLabel: 'Billing', description: 'High-value deal pipeline', icon: 'CreditCard' },
  { id: 'BILL-04', name: 'Payment Methods', category: 'BILL', categoryLabel: 'Billing', description: 'Manage payment methods', icon: 'CreditCard' },
  { id: 'BILL-05', name: 'Invoice History', category: 'BILL', categoryLabel: 'Billing', description: 'View and download invoices', icon: 'CreditCard' },
  { id: 'BILL-06', name: 'Cost Calculator', category: 'BILL', categoryLabel: 'Billing', description: 'Estimate monthly costs', icon: 'CreditCard' },
  { id: 'BILL-07', name: 'Usage Quota Management', category: 'BILL', categoryLabel: 'Billing', description: 'Set usage quotas per team', icon: 'CreditCard' },
  { id: 'BILL-08', name: 'Deal Pipeline Tracker', category: 'BILL', categoryLabel: 'Billing', description: 'Track licensing deals', icon: 'CreditCard' },
  { id: 'BILL-09', name: 'Milestone Tracker', category: 'BILL', categoryLabel: 'Billing', description: 'Track deal milestones', icon: 'CreditCard' },
  { id: 'BILL-10', name: 'Royalty Calculator', category: 'BILL', categoryLabel: 'Billing', description: 'Calculate royalty payments', icon: 'CreditCard' },
  { id: 'BILL-11', name: 'Due Diligence Portal', category: 'BILL', categoryLabel: 'Billing', description: 'Secure portal for licensees', icon: 'CreditCard' },
  { id: 'BILL-12', name: 'Procurement & PO Management', category: 'BILL', categoryLabel: 'Billing', description: 'Purchase order management', icon: 'CreditCard' },
  { id: 'BILL-13', name: 'Billing Contacts', category: 'BILL', categoryLabel: 'Billing', description: 'Manage billing contacts', icon: 'CreditCard' },
  { id: 'BILL-14', name: 'Credit & Adjustments', category: 'BILL', categoryLabel: 'Billing', description: 'Billing credits and adjustments', icon: 'CreditCard' },
  { id: 'BILL-15', name: 'Tax Documents', category: 'BILL', categoryLabel: 'Billing', description: 'Tax documents and W-9', icon: 'CreditCard' },
  { id: 'BILL-16', name: 'Renewal Management', category: 'BILL', categoryLabel: 'Billing', description: 'Manage subscription renewals', icon: 'CreditCard' },
  // INV
  { id: 'INV-01', name: 'Investment Thesis Builder', category: 'INV', categoryLabel: 'Investor', description: 'Build data-backed investment thesis', icon: 'TrendingUp' },
  { id: 'INV-02', name: 'Technology Landscape Map', category: 'INV', categoryLabel: 'Investor', description: 'DrugOS vs competitors landscape', icon: 'TrendingUp' },
  { id: 'INV-03', name: 'Pipeline Success Predictor', category: 'INV', categoryLabel: 'Investor', description: 'AI pipeline success prediction', icon: 'TrendingUp' },
  { id: 'INV-04', name: 'Market Sizing Dashboard', category: 'INV', categoryLabel: 'Investor', description: 'Market opportunity analysis', icon: 'TrendingUp' },
  { id: 'INV-05', name: 'Comparable Company Analysis', category: 'INV', categoryLabel: 'Investor', description: 'Compare DrugOS to peers', icon: 'TrendingUp' },
  { id: 'INV-06', name: 'DrugOS Moat Analysis', category: 'INV', categoryLabel: 'Investor', description: 'Data flywheel moat analysis', icon: 'TrendingUp' },
  { id: 'INV-07', name: 'Financial Projections', category: 'INV', categoryLabel: 'Investor', description: 'Revenue and growth projections', icon: 'TrendingUp' },
  { id: 'INV-08', name: 'Deal Value Calculator', category: 'INV', categoryLabel: 'Investor', description: 'Calculate deal NPV/rNPV', icon: 'TrendingUp' },
  // ADMIN
  { id: 'ADMIN-01', name: 'User Management', category: 'ADMIN', categoryLabel: 'Admin', description: 'Manage users and access', icon: 'Shield' },
  { id: 'ADMIN-02', name: 'Roles & Permissions', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure roles and permissions', icon: 'Shield' },
  { id: 'ADMIN-03', name: 'SSO Configuration', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure SAML/OIDC SSO', icon: 'Shield' },
  { id: 'ADMIN-04', name: 'SCIM Provisioning', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure SCIM user provisioning', icon: 'Shield' },
  { id: 'ADMIN-05', name: 'Department Management', category: 'ADMIN', categoryLabel: 'Admin', description: 'Manage departments and teams', icon: 'Shield' },
  { id: 'ADMIN-06', name: 'Workspace Configuration', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure workspaces', icon: 'Shield' },
  { id: 'ADMIN-07', name: 'Feature Flags', category: 'ADMIN', categoryLabel: 'Admin', description: 'Manage feature flags', icon: 'Shield' },
  { id: 'ADMIN-08', name: 'Data Residency', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure data residency', icon: 'Shield' },
  { id: 'ADMIN-09', name: 'Custom Domain', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure custom domain', icon: 'Shield' },
  { id: 'ADMIN-10', name: 'Branding & White-Label', category: 'ADMIN', categoryLabel: 'Admin', description: 'Customize branding', icon: 'Shield' },
  { id: 'ADMIN-11', name: 'Integration Settings', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure integrations', icon: 'Shield' },
  { id: 'ADMIN-12', name: 'Email Templates', category: 'ADMIN', categoryLabel: 'Admin', description: 'Customize email templates', icon: 'Shield' },
  { id: 'ADMIN-13', name: 'Notification Settings', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure system notifications', icon: 'Shield' },
  { id: 'ADMIN-14', name: 'Security Settings', category: 'ADMIN', categoryLabel: 'Admin', description: 'Security configuration', icon: 'Shield' },
  { id: 'ADMIN-15', name: 'API Key Management', category: 'ADMIN', categoryLabel: 'Admin', description: 'Admin API key management', icon: 'Shield' },
  { id: 'ADMIN-16', name: 'Audit Log Viewer', category: 'ADMIN', categoryLabel: 'Admin', description: 'View audit logs', icon: 'Shield' },
  { id: 'ADMIN-17', name: 'Access Review', category: 'ADMIN', categoryLabel: 'Admin', description: 'Periodic access review', icon: 'Shield' },
  { id: 'ADMIN-18', name: 'E-Signature Config', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure e-signatures', icon: 'Shield' },
  { id: 'ADMIN-19', name: 'GxP Environment Mode', category: 'ADMIN', categoryLabel: 'Admin', description: 'Enable GxP validated mode', icon: 'Shield' },
  { id: 'ADMIN-20', name: 'Data Classification', category: 'ADMIN', categoryLabel: 'Admin', description: 'Configure data classification', icon: 'Shield' },
  { id: 'ADMIN-21', name: 'License Management', category: 'ADMIN', categoryLabel: 'Admin', description: 'Manage software licenses', icon: 'Shield' },
  { id: 'ADMIN-22', name: 'Backup & Recovery', category: 'ADMIN', categoryLabel: 'Admin', description: 'Backup and recovery settings', icon: 'Shield' },
  { id: 'ADMIN-23', name: 'IP Allowlist', category: 'ADMIN', categoryLabel: 'Admin', description: 'IP address allowlisting', icon: 'Shield' },
  { id: 'ADMIN-24', name: 'Session Policies', category: 'ADMIN', categoryLabel: 'Admin', description: 'Session timeout and policies', icon: 'Shield' },
  { id: 'ADMIN-25', name: 'Two-Factor Policies', category: 'ADMIN', categoryLabel: 'Admin', description: '2FA policy configuration', icon: 'Shield' },
  { id: 'ADMIN-26', name: 'Deletion & Retention', category: 'ADMIN', categoryLabel: 'Admin', description: 'Data deletion and retention policies', icon: 'Shield' },
  // LEGAL
  { id: 'LEGAL-01', name: 'Terms & Privacy', category: 'LEGAL', categoryLabel: 'Legal', description: 'Terms of service and privacy policy', icon: 'Scale' },
  { id: 'LEGAL-02', name: 'Data Processing Agreements', category: 'LEGAL', categoryLabel: 'Legal', description: 'DPA management', icon: 'Scale' },
  { id: 'LEGAL-03', name: 'HIPAA & BAA', category: 'LEGAL', categoryLabel: 'Legal', description: 'HIPAA compliance and BAA', icon: 'Scale' },
  { id: 'LEGAL-04', name: 'Cookie Consent', category: 'LEGAL', categoryLabel: 'Legal', description: 'Cookie consent management', icon: 'Scale' },
  { id: 'LEGAL-05', name: 'GDPR Data Export', category: 'LEGAL', categoryLabel: 'Legal', description: 'GDPR data export requests', icon: 'Scale' },
  { id: 'LEGAL-06', name: 'Data Retention Policy', category: 'LEGAL', categoryLabel: 'Legal', description: 'Data retention configuration', icon: 'Scale' },
  { id: 'LEGAL-07', name: 'FOIA Compliance', category: 'LEGAL', categoryLabel: 'Legal', description: 'FOIA compliance tools', icon: 'Scale' },
  { id: 'LEGAL-08', name: 'Sub-Processor List', category: 'LEGAL', categoryLabel: 'Legal', description: 'Sub-processor registry', icon: 'Scale' },
  { id: 'LEGAL-09', name: 'PHI Audit Log', category: 'LEGAL', categoryLabel: 'Legal', description: 'PHI access audit trail', icon: 'Scale' },
  { id: 'LEGAL-10', name: 'PHI Breach Notification', category: 'LEGAL', categoryLabel: 'Legal', description: 'Breach notification workflow', icon: 'Scale' },
  { id: 'LEGAL-11', name: 'HIPAA Training', category: 'LEGAL', categoryLabel: 'Legal', description: 'HIPAA training tracker', icon: 'Scale' },
  { id: 'LEGAL-12', name: 'De-Identification Tool', category: 'LEGAL', categoryLabel: 'Legal', description: 'Data de-identification tool', icon: 'Scale' },
  { id: 'LEGAL-13', name: 'Consent Management', category: 'LEGAL', categoryLabel: 'Legal', description: 'User consent management', icon: 'Scale' },
  { id: 'LEGAL-14', name: 'Risk Assessment', category: 'LEGAL', categoryLabel: 'Legal', description: 'DPIA and risk assessments', icon: 'Scale' },
  { id: 'LEGAL-15', name: 'Incident Response', category: 'LEGAL', categoryLabel: 'Legal', description: 'Security incident response', icon: 'Scale' },
  { id: 'LEGAL-16', name: 'Compliance Calendar', category: 'LEGAL', categoryLabel: 'Legal', description: 'Compliance deadlines calendar', icon: 'Scale' },
  { id: 'LEGAL-17', name: 'Policy Templates', category: 'LEGAL', categoryLabel: 'Legal', description: 'Legal policy templates', icon: 'Scale' },
  // DEV
  { id: 'DEV-01', name: 'API Documentation', category: 'DEV', categoryLabel: 'Developer', description: 'API reference documentation', icon: 'Code' },
  { id: 'DEV-02', name: 'API Key Generation', category: 'DEV', categoryLabel: 'Developer', description: 'Generate and manage API keys', icon: 'Code' },
  { id: 'DEV-03', name: 'API Usage Dashboard', category: 'DEV', categoryLabel: 'Developer', description: 'API usage metrics', icon: 'Code' },
  { id: 'DEV-04', name: 'API Playground', category: 'DEV', categoryLabel: 'Developer', description: 'Interactive API testing', icon: 'Code' },
  { id: 'DEV-05', name: 'Webhook Configuration', category: 'DEV', categoryLabel: 'Developer', description: 'Configure webhooks', icon: 'Code' },
  { id: 'DEV-06', name: 'SDK Downloads', category: 'DEV', categoryLabel: 'Developer', description: 'Download SDKs and libraries', icon: 'Code' },
  { id: 'DEV-07', name: 'Rate Limit Monitor', category: 'DEV', categoryLabel: 'Developer', description: 'Monitor API rate limits', icon: 'Code' },
  { id: 'DEV-08', name: 'API Changelog', category: 'DEV', categoryLabel: 'Developer', description: 'API version history', icon: 'Code' },
  { id: 'DEV-09', name: 'Integration Examples', category: 'DEV', categoryLabel: 'Developer', description: 'Code examples and tutorials', icon: 'Code' },
  { id: 'DEV-10', name: 'GraphQL Explorer', category: 'DEV', categoryLabel: 'Developer', description: 'Interactive GraphQL explorer', icon: 'Code' },
  { id: 'DEV-11', name: 'Batch API Upload', category: 'DEV', categoryLabel: 'Developer', description: 'Batch API data upload', icon: 'Code' },
  { id: 'DEV-12', name: 'API Error Codes', category: 'DEV', categoryLabel: 'Developer', description: 'Error code reference', icon: 'Code' },
  { id: 'DEV-13', name: 'Custom Model Deployment', category: 'DEV', categoryLabel: 'Developer', description: 'Deploy custom ML models', icon: 'Code' },
  { id: 'DEV-14', name: 'Data Export API', category: 'DEV', categoryLabel: 'Developer', description: 'Data export endpoints', icon: 'Code' },
  { id: 'DEV-15', name: 'Webhook Event Log', category: 'DEV', categoryLabel: 'Developer', description: 'Webhook delivery log', icon: 'Code' },
  // SET
  { id: 'SET-01', name: 'Profile Settings', category: 'SET', categoryLabel: 'Settings', description: 'User profile settings', icon: 'Settings' },
  { id: 'SET-02', name: 'Account Security', category: 'SET', categoryLabel: 'Settings', description: 'Password and security settings', icon: 'Settings' },
  { id: 'SET-03', name: 'Notification Preferences', category: 'SET', categoryLabel: 'Settings', description: 'Configure notifications', icon: 'Settings' },
  { id: 'SET-04', name: 'Display Preferences', category: 'SET', categoryLabel: 'Settings', description: 'Theme and display settings', icon: 'Settings' },
  { id: 'SET-05', name: 'API Token Management', category: 'SET', categoryLabel: 'Settings', description: 'Manage personal API tokens', icon: 'Settings' },
  { id: 'SET-06', name: 'Connected Accounts', category: 'SET', categoryLabel: 'Settings', description: 'Third-party account connections', icon: 'Settings' },
  { id: 'SET-07', name: 'Data Export', category: 'SET', categoryLabel: 'Settings', description: 'Export personal data', icon: 'Settings' },
  { id: 'SET-08', name: 'Account Deletion', category: 'SET', categoryLabel: 'Settings', description: 'Delete account and data', icon: 'Settings' },
  { id: 'SET-09', name: 'Organization Profile', category: 'SET', categoryLabel: 'Settings', description: 'Org profile settings', icon: 'Settings' },
  { id: 'SET-10', name: 'Billing Contact', category: 'SET', categoryLabel: 'Settings', description: 'Billing contact information', icon: 'Settings' },
  { id: 'SET-11', name: 'Accessibility Settings', category: 'SET', categoryLabel: 'Settings', description: 'Accessibility configuration', icon: 'Settings' },
  { id: 'SET-12', name: 'Language & Region', category: 'SET', categoryLabel: 'Settings', description: 'Language and timezone', icon: 'Settings' },
  { id: 'SET-13', name: 'Session Management', category: 'SET', categoryLabel: 'Settings', description: 'Active sessions management', icon: 'Settings' },
  { id: 'SET-14', name: 'Two-Factor Auth Setup', category: 'SET', categoryLabel: 'Settings', description: '2FA configuration', icon: 'Settings' },
  { id: 'SET-15', name: 'Email Preferences', category: 'SET', categoryLabel: 'Settings', description: 'Email communication preferences', icon: 'Settings' },
  // SUPP
  { id: 'SUPP-01', name: 'Help Center', category: 'SUPP', categoryLabel: 'Support', description: 'Self-service help center', icon: 'HelpCircle' },
  { id: 'SUPP-02', name: 'Documentation', category: 'SUPP', categoryLabel: 'Support', description: 'Product documentation', icon: 'HelpCircle' },
  { id: 'SUPP-03', name: 'Tutorials & Guides', category: 'SUPP', categoryLabel: 'Support', description: 'Step-by-step tutorials', icon: 'HelpCircle' },
  { id: 'SUPP-04', name: 'FAQ', category: 'SUPP', categoryLabel: 'Support', description: 'Frequently asked questions', icon: 'HelpCircle' },
  { id: 'SUPP-05', name: 'Contact Support', category: 'SUPP', categoryLabel: 'Support', description: 'Contact support team', icon: 'HelpCircle' },
  { id: 'SUPP-06', name: 'Ticket Management', category: 'SUPP', categoryLabel: 'Support', description: 'Support ticket management', icon: 'HelpCircle' },
  { id: 'SUPP-07', name: 'Knowledge Base', category: 'SUPP', categoryLabel: 'Support', description: 'Searchable knowledge base', icon: 'HelpCircle' },
  { id: 'SUPP-08', name: 'Release Notes', category: 'SUPP', categoryLabel: 'Support', description: 'Product release notes', icon: 'HelpCircle' },
  { id: 'SUPP-09', name: 'Video Tutorials', category: 'SUPP', categoryLabel: 'Support', description: 'Video walkthroughs', icon: 'HelpCircle' },
  { id: 'SUPP-10', name: 'Community Forum', category: 'SUPP', categoryLabel: 'Support', description: 'Community discussion forum', icon: 'HelpCircle' },
  { id: 'SUPP-11', name: 'Feedback & Feature Request', category: 'SUPP', categoryLabel: 'Support', description: 'Submit feedback and requests', icon: 'HelpCircle' },
  { id: 'SUPP-12', name: 'Onboarding Checklist', category: 'SUPP', categoryLabel: 'Support', description: 'New user onboarding guide', icon: 'HelpCircle' },
  { id: 'SUPP-13', name: 'System Requirements', category: 'SUPP', categoryLabel: 'Support', description: 'Technical requirements', icon: 'HelpCircle' },
  // MISC
  { id: 'MISC-01', name: '404 Error Page', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Page not found', icon: 'FileQuestion' },
  { id: 'MISC-02', name: '500 Error Page', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Server error page', icon: 'FileQuestion' },
  { id: 'MISC-03', name: 'Maintenance Mode', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'System maintenance page', icon: 'FileQuestion' },
  { id: 'MISC-04', name: 'Rate Limit Warning', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Rate limit exceeded warning', icon: 'FileQuestion' },
  { id: 'MISC-05', name: 'Upgrade Prompt Modal', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Upgrade plan prompt', icon: 'FileQuestion' },
  { id: 'MISC-06', name: 'Feature Locked Overlay', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Feature behind paywall', icon: 'FileQuestion' },
  { id: 'MISC-07', name: 'Loading Skeleton', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Loading skeleton state', icon: 'FileQuestion' },
  { id: 'MISC-08', name: 'Empty State', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'No results empty state', icon: 'FileQuestion' },
  { id: 'MISC-09', name: 'First-Time User Tour', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Guided product tour', icon: 'FileQuestion' },
  { id: 'MISC-10', name: 'Cookie Consent Banner', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Cookie consent banner', icon: 'FileQuestion' },
  { id: 'MISC-11', name: 'Announcement Banner', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'System announcement banner', icon: 'FileQuestion' },
  { id: 'MISC-12', name: 'Print View Report', category: 'MISC', categoryLabel: 'Miscellaneous', description: 'Print-optimized view', icon: 'FileQuestion' },
];

export function getScreenById(id: string): ScreenMeta | undefined {
  return screens.find(s => s.id === id);
}

export function getScreensByCategory(category: string): ScreenMeta[] {
  return screens.filter(s => s.category === category);
}
