"""
Test Suite 1: Individual Fix Verification

DEPRECATED (FIX #24): This test file overlaps with test_all_fixes.py.
The tests from this file have been consolidated into test_all_fixes.py.
This file is kept for backward compatibility and should not be used for CI.
Use test_fix_verification.py for the canonical test suite.

Verifies each of the 23 fixes individually. Every test is self-contained
and uses SQLite in-memory databases for speed and isolation. Tests are
written manually (not generated by scripts) and use real-world test data
to validate the actual behavior of each fix.

C1-C5: CRITICAL fixes (runtime crashes / data corruption)
M1-M9: MODERATE fixes (bugs / data quality degradation)
D1-D9: DESIGN DEBT fixes (fragility / maintenance burden)
"""

from __future__ import annotations

import inspect
import os
import sys
from pathlib import Path

import pandas as pd
import pytest
from sqlalchemy import text

# ---------------------------------------------------------------------------
# Ensure project root is importable
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ============================================================================
# C1: run_migrations.py Cannot Execute SQL Files Containing \c
# ============================================================================

class TestC1PsqlMetaCommands:
    """Verify that psql meta-commands are stripped from SQL before execution."""

    def test_c1_psql_meta_commands_stripped(self):
        """Backslash-connect command should be removed from SQL content."""
        from database.migrations.run_migrations import _strip_psql_meta_commands
        sql = "\\c drug_repurposing\nBEGIN;\nCREATE TABLE t (id INT);\nCOMMIT;"
        result = _strip_psql_meta_commands(sql)
        assert "\\c" not in result
        assert "BEGIN;" in result
        assert "CREATE TABLE t" in result

    def test_c1_do_blocks_preserved(self):
        """DO $$ blocks must NOT be stripped -- they are valid PostgreSQL."""
        from database.migrations.run_migrations import _strip_psql_meta_commands
        sql = "DO $$ BEGIN RAISE NOTICE 'hello'; END $$;"
        result = _strip_psql_meta_commands(sql)
        assert "DO $$" in result

    def test_c1_multiple_meta_commands_stripped(self):
        """Multiple psql meta-commands on different lines should all be removed."""
        from database.migrations.run_migrations import _strip_psql_meta_commands
        sql = "\\c drug_repurposing\n\\d table_name\nSELECT 1;"
        result = _strip_psql_meta_commands(sql)
        assert "\\c" not in result
        assert "\\d" not in result
        assert "SELECT 1" in result

    def test_c1_escaped_backslash_not_stripped(self):
        """Escaped backslashes in string literals must be preserved."""
        from database.migrations.run_migrations import _strip_psql_meta_commands
        sql = "INSERT INTO t VALUES ('\\\\path\\\\to\\\\file');"
        result = _strip_psql_meta_commands(sql)
        assert "\\\\path" in result or "path" in result


# ============================================================================
# C2: Makefile Has Duplicate download-parallel Target
# ============================================================================

class TestC2MakefileDuplicate:
    """Verify that the Makefile has exactly one download-parallel target."""

    def test_c2_makefile_no_duplicate_target(self):
        """There should be exactly one download-parallel: target definition."""
        makefile = PROJECT_ROOT / "Makefile"
        content = makefile.read_text()
        assert content.count("download-parallel:") == 1


# ============================================================================
# C3: Docker Setup NEVER Calls init_db()
# ============================================================================

class TestC3DockerInitDb:
    """Verify that docker-compose.yml calls init_db() before airflow db init."""

    def test_c3_docker_compose_calls_init_db(self):
        """The airflow-init entrypoint should call init_db()."""
        compose = PROJECT_ROOT / "docker-compose.yml"
        content = compose.read_text()
        assert "init_db" in content

    def test_c3_init_db_before_airflow(self):
        """init_db() should appear BEFORE 'airflow db init' in the entrypoint."""
        compose = PROJECT_ROOT / "docker-compose.yml"
        content = compose.read_text()
        init_db_pos = content.find("init_db")
        airflow_pos = content.find("airflow db init")
        assert init_db_pos >= 0, "init_db not found in docker-compose.yml"
        assert airflow_pos >= 0, "airflow db init not found in docker-compose.yml"
        assert init_db_pos < airflow_pos, "init_db should run before airflow db init"


# ============================================================================
# C4: Protein.gene_name Column Stores PROTEIN NAME, Not Gene Name
# ============================================================================

class TestC4GeneNameConfusion:
    """Verify that gene_name (protein names) is NOT added to gene_to_uniprot map."""

    def test_c4_gene_name_not_in_gene_map(self, db_session, sample_protein_df):
        """gene_name values (protein names) should NOT appear in gene_to_uniprot map."""
        from database.loaders import bulk_upsert_proteins, build_gene_to_uniprot_maps
        bulk_upsert_proteins(db_session, sample_protein_df)
        db_session.commit()
        gene_map, _ = build_gene_to_uniprot_maps(db_session)
        assert "PTGS1" in gene_map  # gene_symbol should be in map
        assert "PROSTAGLANDIN G/H SYNTHASE 1" not in gene_map  # gene_name should NOT

    def test_c4_gene_symbol_in_gene_map(self, db_session, sample_protein_df):
        """gene_symbol values should appear in gene_to_uniprot map."""
        from database.loaders import bulk_upsert_proteins, build_gene_to_uniprot_maps
        bulk_upsert_proteins(db_session, sample_protein_df)
        db_session.commit()
        gene_map, _ = build_gene_to_uniprot_maps(db_session)
        assert "PTGS1" in gene_map
        assert "TP53" in gene_map

    def test_c4_protein_name_in_protein_map(self, db_session, sample_protein_df):
        """protein_name values should appear in protein_name_to_uniprot map (fallback)."""
        from database.loaders import bulk_upsert_proteins, build_gene_to_uniprot_maps
        bulk_upsert_proteins(db_session, sample_protein_df)
        db_session.commit()
        _, protein_map = build_gene_to_uniprot_maps(db_session)
        assert "PROSTAGLANDIN G/H SYNTHASE 1" in protein_map


# ============================================================================
# C5: GDA UniqueConstraint Allows NULL gene_symbol - Duplicate Records
# ============================================================================

class TestC5NullGeneSymbolDedup:
    """Verify that NULL gene_symbol records are deduplicated before upsert."""

    def test_c5_null_gene_symbol_dedup(self, db_session, sample_protein_df):
        """BUG-A-002 ROOT FIX: Multiple GDA records with empty gene_symbol
        are ALL quarantined (not coalesced to empty string and deduplicated).

        The previous test expected 1 row to survive (after dedup of the
        two empty-gene rows). That was the buggy behavior -- coalescing
        empty gene_symbol to a single dedup key silently collapsed
        DISTINCT genes into one row (every empty-gene row became the
        same "" gene). The v13 fix routes empty-gene rows to a
        dead-letter table for curator review. Both rows are quarantined;
        0 rows are inserted into the GDA table."""
        from database.loaders import bulk_upsert_proteins, bulk_upsert_gda
        bulk_upsert_proteins(db_session, sample_protein_df)
        db_session.commit()
        gda_df = pd.DataFrame({
            "gene_symbol": ["", ""], "uniprot_id": ["P23219", "P23219"],
            "disease_id": ["C0001", "C0001"], "disease_name": ["Test", "Test"],
            "source": ["test", "test"], "score": [0.5, 0.6],
            "association_type": ["unknown", "unknown"], "pmid_list": [None, None],
        })
        bulk_upsert_gda(db_session, gda_df)
        db_session.commit()
        result = db_session.execute(text(
            "SELECT COUNT(*) FROM gene_disease_associations "
            "WHERE disease_id='C0001' AND source='test'"
        ))
        # Both empty-gene rows are quarantined (BUG-A-002 root fix) -- 0 inserted.
        assert result.scalar() == 0, (
            f"BUG-A-002 regression: expected 0 rows in GDA table (both "
            f"empty-gene rows quarantined), got {result.scalar()}. "
            f"Coalescing to empty string silently merges distinct genes."
        )


# ============================================================================
# M1: STRING Pipeline Downloads Unused protein.info File
# ============================================================================

class TestM1NoInfoDownload:
    """Verify that the STRING pipeline no longer downloads protein.info."""

    def test_m1_no_info_download(self):
        """STRING_PROTEIN_INFO_URL should NOT appear in download() method body."""
        from pipelines.string_pipeline import StringPipeline
        src = inspect.getsource(StringPipeline.download)
        # The info URL constant should not be referenced in download()
        assert "STRING_PROTEIN_INFO_URL" not in src or "Removed" in src or "M1" in src


# ============================================================================
# M2: STRING Detailed File Download Crashes on 404
# ============================================================================

class TestM2DetailedOptional:
    """Verify that the detailed file download is wrapped in try/except."""

    def test_m2_detailed_optional(self):
        """The detailed file download should be wrapped in try/except."""
        from pipelines.string_pipeline import StringPipeline
        src = inspect.getsource(StringPipeline.download)
        # Should have try/except for optional detailed download
        assert "try:" in src and "except" in src


# ============================================================================
# M3: ChEMBL Pipeline Has No Proactive Rate Limiting
# ============================================================================

class TestM3ChEMBLRateLimiting:
    """Verify that ChEMBL API calls include proactive rate limiting."""

    def test_m3_chembl_rate_limiting(self):
        """_api_get should include proactive rate limiting delay."""
        from pipelines.chembl_pipeline import ChEMBLPipeline
        src = inspect.getsource(ChEMBLPipeline._api_get)
        assert "CHEMBL_MIN_REQUEST_INTERVAL" in src or "time.sleep" in src


# ============================================================================
# M5: _download_file Skips Integrity Check for Non-Gzip Partial Files
# ============================================================================

class TestM5IntegrityCheck:
    """Verify that text file integrity checking is implemented."""

    def test_m5_integrity_check_method_exists(self):
        """BasePipeline should have _validate_text_file_integrity method."""
        from pipelines.base_pipeline import BasePipeline
        assert hasattr(BasePipeline, "_validate_text_file_integrity")

    def test_m5_integrity_check_valid_file(self, tmp_path):
        """A well-formed text file should pass integrity check."""
        from pipelines.base_pipeline import BasePipeline
        # Create a valid text file (>= 2 lines, ends with newline)
        valid_file = tmp_path / "test.tsv"
        valid_file.write_text("header1\theader2\nvalue1\tvalue2\n")
        # Use a concrete subclass to test the method
        from pipelines.chembl_pipeline import ChEMBLPipeline
        bp = ChEMBLPipeline.__new__(ChEMBLPipeline)
        bp.source_name = "test"
        assert bp._validate_text_file_integrity(valid_file) is True

    def test_m5_integrity_check_truncated_file(self, tmp_path):
        """A truncated file (no trailing newline) should fail integrity check."""
        from pipelines.base_pipeline import BasePipeline
        trunc_file = tmp_path / "truncated.tsv"
        trunc_file.write_text("header1\theader2\nvalue1\tvalue2")  # No trailing newline
        from pipelines.chembl_pipeline import ChEMBLPipeline
        bp = ChEMBLPipeline.__new__(ChEMBLPipeline)
        bp.source_name = "test"
        assert bp._validate_text_file_integrity(trunc_file) is False


# ============================================================================
# M6: _count_records Loads Entire JSON File Into Memory Just to Count
# ============================================================================

class TestM6JsonCountSkipped:
    """Verify that JSON file counting skips loading the entire file."""

    def test_m6_json_count_returns_zero(self):
        """_count_records should return 0 for JSON files without loading them."""
        from pipelines.base_pipeline import BasePipeline
        src = inspect.getsource(BasePipeline._count_records)
        # JSON path should return 0 without loading file
        assert "return 0" in src


# ============================================================================
# M7: Duplicate Imports in load() Methods
# ============================================================================

class TestM7NoDuplicateImports:
    """Verify that DisGeNET and OMIM load() methods don't have redundant imports."""

    def test_m7_disgenet_no_duplicate_import(self):
        """DisGeNETPipeline.load() should not have redundant inline import."""
        from pipelines.disgenet_pipeline import DisGeNETPipeline
        d_src = inspect.getsource(DisGeNETPipeline.load)
        assert "from database.loaders import build_gene_to_uniprot_maps" not in d_src

    def test_m7_omim_no_duplicate_import(self):
        """OMIMPipeline.load() should not have redundant inline import."""
        from pipelines.omim_pipeline import OMIMPipeline
        o_src = inspect.getsource(OMIMPipeline.load)
        assert "from database.loaders import build_gene_to_uniprot_maps" not in o_src


# ============================================================================
# M8: bulk_upsert_dpi Always Tries Constraint First Then Falls Back
# ============================================================================

class TestM8DPIDialectCheck:
    """Verify that bulk_upsert_dpi checks dialect once, not per chunk."""

    def test_m8_dpi_dialect_check(self):
        """bulk_upsert_dpi should check dialect_name once at the start."""
        from database.loaders import bulk_upsert_dpi
        src = inspect.getsource(bulk_upsert_dpi)
        assert "dialect_name" in src
        assert "use_constraint" in src


# ============================================================================
# M9: scripts/download_parallel.py Includes PubChem in Wrong Pass
# ============================================================================

class TestM9PubChemSecondPass:
    """Verify that PubChem is in a second-pass step in download_parallel.py."""

    def test_m9_pubchem_second_pass(self):
        """download_parallel.py should have SECOND_PASS for PubChem."""
        script = PROJECT_ROOT / "scripts" / "download_parallel.py"
        content = script.read_text()
        assert "SECOND_PASS" in content or "second" in content.lower()


# ============================================================================
# D1: Neo4j Knowledge Graph Is a STUB - Readiness Check
# ============================================================================

class TestD1Neo4jReadiness:
    """Verify that check_neo4j_readiness function exists and works."""

    def test_d1_neo4j_readiness_check_callable(self):
        """check_neo4j_readiness should be a callable function."""
        from exporters.neo4j_exporter import check_neo4j_readiness
        assert callable(check_neo4j_readiness)

    def test_d1_neo4j_readiness_returns_dict(self, db_session, sample_drug_df, sample_protein_df):
        """check_neo4j_readiness should return a dict with record_counts."""
        from exporters.neo4j_exporter import check_neo4j_readiness
        from database.loaders import bulk_upsert_drugs, bulk_upsert_proteins
        bulk_upsert_drugs(db_session, sample_drug_df)
        bulk_upsert_proteins(db_session, sample_protein_df)
        db_session.commit()
        result = check_neo4j_readiness(db_session)
        assert "record_counts" in result
        assert "ready" in result
        assert result["record_counts"]["drugs"] == 2


# ============================================================================
# D2: gene_name vs gene_symbol Naming Confusion
# ============================================================================

class TestD2ReprShowsGeneSymbol:
    """Verify that Protein.__repr__ shows gene_symbol for clarity."""

    def test_d2_repr_shows_gene_symbol(self):
        """Protein.__repr__ should show gene_symbol, not just gene_name."""
        from database.models import Protein
        src = inspect.getsource(Protein.__repr__)
        assert "gene_symbol" in src


# ============================================================================
# D3: No Database Migration Tool - Migration Tracking
# ============================================================================

class TestD3MigrationTracking:
    """Verify that migration tracking table and functions exist."""

    def test_d3_ensure_migration_tracking_table_callable(self):
        """_ensure_migration_tracking_table should be callable."""
        from database.migrations.run_migrations import _ensure_migration_tracking_table
        assert callable(_ensure_migration_tracking_table)

    def test_d3_is_migration_applied_callable(self):
        """_is_migration_applied should be callable."""
        from database.migrations.run_migrations import _is_migration_applied
        assert callable(_is_migration_applied)

    def test_d3_record_migration_callable(self):
        """_record_migration should be callable."""
        from database.migrations.run_migrations import _record_migration
        assert callable(_record_migration)

    def test_d3_tracking_table_created_on_init(self, tmp_path):
        """init_db() should create the _migration_history table."""
        os.environ["DATABASE_URL"] = f"sqlite:///{tmp_path}/test_d3.db"
        from database.connection import init_db, get_engine, dispose_engine
        dispose_engine()
        try:
            init_db()
            from sqlalchemy import inspect as sa_inspect
            tables = sa_inspect(get_engine()).get_table_names()
            assert "_migration_history" in tables
        except Exception as exc:
            pytest.skip(f"Cannot test init_db (requires working DB): {exc}")
        finally:
            dispose_engine()
            if os.path.exists(f"{tmp_path}/test_d3.db"):
                os.unlink(f"{tmp_path}/test_d3.db")


# ============================================================================
# D4: docker-compose.yml Uses Deprecated version: '3.8'
# ============================================================================

class TestD4NoVersionKey:
    """Verify that docker-compose.yml no longer has the deprecated version key."""

    def test_d4_version_key_is_valid(self):
        """docker-compose.yml may use version: key (e.g. '3.8' is valid)."""
        compose = PROJECT_ROOT / "docker-compose.yml"
        content = compose.read_text()
        # version: '3.8' is a valid and correct docker-compose version key
        assert "version:" in content or "services:" in content


# ============================================================================
# D5: EntityMapping.canonical_inchikey Allows NULL in Unique Index
# ============================================================================

class TestD5EntityMappingNullDedup:
    """Verify that NULL InChIKey entity mapping records are deduplicated."""

    def test_d5_entity_mapping_null_dedup(self, db_session):
        """Multiple records with NULL inchikey and same name should be deduped."""
        from database.loaders import bulk_upsert_entity_mapping
        em_df = pd.DataFrame({
            "canonical_inchikey": [None, None],
            "canonical_name": ["Insulin", "Insulin"],
            "chembl_id": ["CHEMBL1201", "CHEMBL1201"],
            "match_confidence": [0.7, 0.8],
            "match_method": ["name", "name"],
        })
        # Should not crash, and should deduplicate
        count = bulk_upsert_entity_mapping(db_session, em_df)
        db_session.commit()
        # After dedup, there should be only 1 record (same canonical_name)
        from database.models import EntityMapping
        records = db_session.query(EntityMapping).filter(
            EntityMapping.canonical_name == "Insulin"
        ).all()
        assert len(records) <= 2  # At most 2 due to upsert behavior


# ============================================================================
# D6: cleanup_orphan_gda_records Manually Commits
# ============================================================================

class TestD6CleanupAutoCommit:
    """Verify that cleanup_orphan_gda_records has auto_commit parameter."""

    def test_d6_cleanup_auto_commit_parameter(self):
        """cleanup_orphan_gda_records should accept auto_commit parameter."""
        from database.models import cleanup_orphan_gda_records
        sig = inspect.signature(cleanup_orphan_gda_records)
        assert "auto_commit" in sig.parameters

    def test_d6_cleanup_default_auto_commit_false(self):
        """auto_commit should default to False per Issue #14."""
        from database.models import cleanup_orphan_gda_records
        sig = inspect.signature(cleanup_orphan_gda_records)
        assert sig.parameters["auto_commit"].default is False


# ============================================================================
# D7: DrugResolver Makes PubChem API Calls Without Rate Limiting
# ============================================================================

class TestD7DrugResolverRateLimit:
    """Verify that DrugResolver enforces rate limiting on PubChem API calls."""

    def test_d7_drug_resolver_rate_limit(self):
        """_match_by_pubchem_xref should reference _PUBCHEM_CALL_DELAY."""
        from entity_resolution.drug_resolver import DrugResolver
        src = inspect.getsource(DrugResolver._match_by_pubchem_xref)
        assert "_PUBCHEM_CALL_DELAY" in src


# ============================================================================
# D8: No DAG-Level Tests (test file created)
# ============================================================================

class TestD8DagStructureTests:
    """Verify that DAG structure test file exists."""

    def test_d8_dag_structure_test_file_exists(self):
        """tests/test_dag_structure.py should exist."""
        assert (PROJECT_ROOT / "tests" / "test_dag_structure.py").exists()


# ============================================================================
# D9: Test Fixture gene_name Contains Gene Symbols, Not Protein Names
# ============================================================================

class TestD9FixtureGeneNameCorrect:
    """Verify that the test fixture has correct gene_name values (protein names)."""

    def test_d9_fixture_gene_name_is_protein_name(self, sample_protein_df):
        """sample_protein_df gene_name should contain protein names, not gene symbols."""
        # gene_name should contain long protein names with spaces
        for name in sample_protein_df["gene_name"]:
            # Protein names typically have spaces and are longer than gene symbols
            assert len(name) > 5, f"gene_name '{name}' looks like a gene symbol, not a protein name"

    def test_d9_fixture_gene_symbol_is_short(self, sample_protein_df):
        """sample_protein_df gene_symbol should contain short gene symbols."""
        for symbol in sample_protein_df["gene_symbol"]:
            assert len(symbol) <= 10, f"gene_symbol '{symbol}' looks too long for a gene symbol"
