# SPDX-License-Identifier: MIT
# © 2024-2026 Autonomous Drug Repurposing Platform — Team Cosmic / VentureLab
"""Type stubs for the entity_resolution package (v1.0.0).

These stubs mirror every public symbol listed in
``entity_resolution.__all__``.  Audit D14-2 — the previous package
had no ``.pyi`` stub, which broke PEP 561 typed-package consumers
(mypy, pyright, IDE autocomplete).
"""

from __future__ import annotations

from typing import (
    Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple, Union,
)
import enum
import logging
import re
from dataclasses import dataclass, field

import pandas as pd

# Version
__version__: str

# Constants
MAPPING_SCHEMA_VERSION: str
INCHIKEY_PATTERN: re.Pattern[str]
SYNTHETIC_INCHIKEY_PREFIX: str
METHOD_CONFIDENCE: Dict[str, float]


# ---------------------------------------------------------------------------
# base.py
# ---------------------------------------------------------------------------

class MatchConfidence(float, enum.Enum):
    INCHIKEY_EXACT: float
    INCHIKEY_CONNECTIVITY: float
    NAME_NORMALIZED: float
    PUBCHEM_XREF: float
    FUZZY: float
    UNIPROT_EXACT: float
    GENE_NAME_ORGANISM: float
    PROTEIN_NAME_FUZZY: float
    UNKNOWN: float

    @classmethod
    def from_method(cls, method: str) -> "MatchConfidence": ...


@dataclass(frozen=True)
class ResolverConfig:
    collapse_stereoisomers: bool
    fuzzy_threshold: float
    fuzzy_max_candidates: int
    pubchem_enabled: bool
    pubchem_rest_base: str
    pubchem_call_delay: float
    pubchem_timeout: float
    pubchem_max_retries: int
    pubchem_api_key: Optional[str]
    pubchem_ca_bundle: Optional[str]
    pubchem_cert_pem: Optional[str]
    pubchem_key_pem: Optional[str]
    pubchem_strict_salt_form: bool
    source_whitelist: Optional[Tuple[str, ...]]
    default_organism: str
    mapping_schema_version: str

    @classmethod
    def from_env(cls, **overrides: Any) -> "ResolverConfig": ...
    def validate(self) -> None: ...
    def to_masked_dict(self) -> Dict[str, Any]: ...


@dataclass
class ResolverStats:
    records_ingested: int
    records_matched: int
    records_created: int
    records_rejected: int
    fuzzy_matches: int
    connectivity_matches: int
    name_matches: int
    inchikey_exact_matches: int
    pubchem_calls: int
    pubchem_successes: int
    pubchem_failures: int
    pubchem_dead_lettered: int
    stereoisomer_collapses: int
    synthetic_keys_generated: int
    duplicate_ids_detected: int
    dead_lettered: int

    def __post_init__(self) -> None: ...
    def inc(self, field_name: str, amount: int = ...) -> None: ...
    def to_dict(self) -> Dict[str, int]: ...
    def reset(self) -> None: ...


class Resolver:
    MAPPING_SCHEMA_VERSION: str

    @property
    def config(self) -> ResolverConfig: ...
    @property
    def stats(self) -> ResolverStats: ...
    @property
    def mapping(self) -> Dict[str, dict]: ...

    def add_source_records(self, records: List[dict], source: str) -> None: ...
    def resolve_single(self, **kwargs: Any) -> Optional[dict]: ...
    def build_mapping(self, **kwargs: Any) -> pd.DataFrame: ...
    def to_dataframe(self, chunksize: Optional[int] = ...) -> pd.DataFrame: ...
    def to_records(self) -> List[dict]: ...
    def to_dict(self) -> Dict[str, dict]: ...
    def to_state_dict(self) -> dict: ...
    @classmethod
    def from_state_dict(cls, state: dict) -> "Resolver": ...
    def to_json(self, path: Optional[str] = ...) -> str: ...
    @classmethod
    def from_json(cls, path_or_text: str) -> "Resolver": ...
    def reset(self) -> None: ...
    def remove_source(self, source: str) -> int: ...
    def get_stats(self) -> Dict[str, int]: ...
    def get_audit_trail(self, canonical_id: str) -> List[dict]: ...
    def find_affected_entities(self, source: str) -> List[str]: ...


def is_valid_inchikey(inchikey: Any) -> bool: ...
def is_synthetic_inchikey(inchikey: Any) -> bool: ...
def make_synthetic_inchikey(normalized_name: str, salt: str = ...) -> str: ...


# ---------------------------------------------------------------------------
# drug_resolver.py
# ---------------------------------------------------------------------------

class DrugResolver(Resolver):
    def __init__(self, config: Optional[ResolverConfig] = ...) -> None: ...

    def add_source_records(self, records: List[dict], source: str) -> None: ...
    def resolve_single(
        self, name: str, inchikey: Optional[str] = ...
    ) -> dict: ...
    def get_canonical_inchikey(self, drug_record: dict) -> Optional[str]: ...
    def build_mapping(
        self,
        chembl_df: pd.DataFrame,
        drugbank_df: pd.DataFrame,
        pubchem_df: pd.DataFrame,
        *,
        reset: bool = ...,
        sources_order: Optional[Sequence[str]] = ...,
    ) -> pd.DataFrame: ...
    def to_dataframe(
        self, chunksize: Optional[int] = ...
    ) -> Union[pd.DataFrame, Iterator[pd.DataFrame]]: ...
    def to_records(self) -> List[dict]: ...
    def to_dict(self) -> Dict[str, dict]: ...
    def to_parquet(self, path: str) -> None: ...
    def to_state_dict(self) -> dict: ...
    @classmethod
    def from_state_dict(cls, state: dict) -> "DrugResolver": ...
    def reset(self) -> None: ...
    def remove_source(self, source: str) -> int: ...
    def get_stats(self) -> Dict[str, int]: ...
    def get_audit_trail(self, canonical_inchikey: str) -> List[dict]: ...
    def find_affected_entities(self, source: str) -> List[str]: ...
    def get_pubchem_failure_count(self) -> int: ...


def build_mapping(
    chembl_df: pd.DataFrame,
    drugbank_df: pd.DataFrame,
    pubchem_df: pd.DataFrame,
    *,
    config: Optional[ResolverConfig] = ...,
    reset: bool = ...,
) -> pd.DataFrame: ...


# ---------------------------------------------------------------------------
# protein_resolver.py
# ---------------------------------------------------------------------------

class ProteinResolver(Resolver):
    def __init__(self, config: Optional[ResolverConfig] = ...) -> None: ...

    def add_source_records(self, records: List[dict], source: str) -> None: ...
    def add_uniprot_records(self, records: List[dict]) -> None: ...
    def add_string_records(self, records: List[dict]) -> None: ...
    def add_chembl_target_records(self, records: List[dict]) -> None: ...
    def resolve_single(
        self,
        uniprot_id: Optional[str] = ...,
        gene_name: Optional[str] = ...,
        string_id: Optional[str] = ...,
        organism: Optional[str] = ...,
    ) -> Optional[dict]: ...
    def build_mapping(
        self,
        uniprot_df: pd.DataFrame,
        string_aliases_df: Optional[pd.DataFrame] = ...,
        string_df: Optional[pd.DataFrame] = ...,
        *,
        reset: bool = ...,
    ) -> pd.DataFrame: ...
    def to_dataframe(
        self, chunksize: Optional[int] = ...
    ) -> Union[pd.DataFrame, Iterator[pd.DataFrame]]: ...
    def to_records(self) -> List[dict]: ...
    def to_dict(self) -> Dict[str, dict]: ...
    def to_parquet(self, path: str) -> None: ...
    def to_state_dict(self) -> dict: ...
    @classmethod
    def from_state_dict(cls, state: dict) -> "ProteinResolver": ...
    def reset(self) -> None: ...
    def remove_source(self, source: str) -> int: ...
    def get_stats(self) -> Dict[str, int]: ...
    def get_audit_trail(self, canonical_id: str) -> List[dict]: ...
    def find_affected_entities(self, source: str) -> List[str]: ...


# ---------------------------------------------------------------------------
# resolver_utils.py
# ---------------------------------------------------------------------------

def normalize_name(name: Any) -> str: ...
def fuzzy_match_score(name1: str, name2: str) -> float: ...
def extract_inchikey_first_block(inchikey: Any) -> Optional[str]: ...
def build_name_index(
    records: List[dict], name_field: str = ...
) -> Dict[str, List[int]]: ...
def build_inchikey_index(
    records: List[dict], inchikey_field: str = ...
) -> Dict[str, List[int]]: ...
def build_canonical_name_index(
    records: Sequence[Any], name_field: str = ...
) -> Dict[str, str]: ...
def build_canonical_inchikey_index(
    records: Sequence[Any], inchikey_field: str = ...
) -> Dict[str, str]: ...
def compute_match_confidence(method: str) -> float: ...
def register_match_method(method: str, confidence: float) -> None: ...
def validate_drug_record(
    record: dict, *, strict: bool = ...
) -> Tuple[bool, List[str]]: ...
def validate_protein_record(
    record: dict, *, strict: bool = ...
) -> Tuple[bool, List[str]]: ...
def find_duplicate_ids(
    records: Sequence[dict],
    id_fields: Sequence[str] = ...,
) -> Dict[str, List[str]]: ...


# ---------------------------------------------------------------------------
# Submodules (D1-4 / D15-1)
# ---------------------------------------------------------------------------

import entity_resolution.base as base
import entity_resolution.drug_resolver as drug_resolver
import entity_resolution.protein_resolver as protein_resolver
import entity_resolution.resolver_utils as resolver_utils


# ---------------------------------------------------------------------------
# Factory + helper functions
# ---------------------------------------------------------------------------

def make_drug_resolver(
    config: Optional[ResolverConfig] = ..., **config_overrides: Any
) -> DrugResolver: ...

def make_protein_resolver(
    config: Optional[ResolverConfig] = ..., **config_overrides: Any
) -> ProteinResolver: ...

def check_dependencies() -> Dict[str, bool]: ...
def is_available() -> bool: ...
def set_log_level(level: Union[str, int]) -> None: ...
def set_log_format(fmt: str = ...) -> None: ...
